### PR TITLE
Core Files/Testing Update and introduce adapter-core

### PR DESCRIPTION
**Pull request by Apollon77**
see https://forum.iobroker.net/post/237344 for more details

### CODE REVIEW

**Comment by SebastianSchultz** [comment]
Hello Apollon,

can you please help here?
I don't know what I have to do :(

**Comment by Apollon77** [comment]
I zhin I solved all merge conflicts ... lets see what testing says :)

**Comment by Apollon77** [comment]
I did one more change

**Comment by Apollon77** [comment]
I can not fix further. Now he is somplaining about missing lib/enet ... and yes this is not there. Please check where this file is!

**Pull request merged**
